-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 23:31:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_samaforte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_samaforte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_samaforte` DEFAULT CHARACTER SET utf8 ;
USE `db_samaforte` ;

-- -----------------------------------------------------
-- Table `db_samaforte`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `hierarquia` TINYINT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC) VISIBLE,
  UNIQUE INDEX `imagem_UNIQUE` (`imagem` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`perfil_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`perfil_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_perfil` INT NOT NULL,
  `id_menu` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_menu_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  INDEX `fk_perfil_menu_menu1_idx` (`id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_menu_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_samaforte`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_menu_menu1`
    FOREIGN KEY (`id_menu`)
    REFERENCES `db_samaforte`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `login` VARCHAR(6) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_samaforte`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`relatorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dataCriacao_UNIQUE` (`dataCriacao` ASC) VISIBLE,
  UNIQUE INDEX `arquivo_UNIQUE` (`arquivo` ASC) VISIBLE,
  INDEX `fk_relatorio_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_samaforte`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataCriacao` DATETIME NOT NULL,
  `dataValidade` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pendente',
  `informacoes` TEXT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamento_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_orcamento_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_samaforte`.`cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `desconto` DECIMAL NULL DEFAULT 0,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  `valor` DECIMAL UNSIGNED NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_orcamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `data_UNIQUE` (`data` ASC) VISIBLE,
  INDEX `fk_venda_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_venda_orcamento1_idx` (`id_orcamento` ASC) VISIBLE,
  CONSTRAINT `fk_venda_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_samaforte`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_orcamento1`
    FOREIGN KEY (`id_orcamento`)
    REFERENCES `db_samaforte`.`orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `nome` VARCHAR(50) NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `quantidadeCritica` INT UNSIGNED NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `fornecedor` VARCHAR(50) NOT NULL,
  `preco` DECIMAL UNSIGNED NOT NULL,
  `custo` DECIMAL UNSIGNED NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_samaforte`.`item_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_samaforte`.`item_orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `preco` DECIMAL UNSIGNED NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `statusVenda` TINYINT(1) NOT NULL DEFAULT 0,
  `id_orcamento` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dataHora_UNIQUE` (`dataHora` ASC) VISIBLE,
  INDEX `fk_item_orcamento_orcamento1_idx` (`id_orcamento` ASC) VISIBLE,
  INDEX `fk_item_orcamento_produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_item_orcamento_orcamento1`
    FOREIGN KEY (`id_orcamento`)
    REFERENCES `db_samaforte`.`orcamento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_orcamento_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `db_samaforte`.`produto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
